[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "1.3.1"
serde = { version = "1.0.228", features = ["derive"]}

macroquad = "0.4.14"
message-io = "0.19.0"

common = { path = "../common" }
serde_json = "1.0.145"
